config/routes.rb
Rails.application.routes.draw do

  get '/dashboard', to: 'dashboard#index'
  get '/results', to: 'results#index'

  root'welcome#index'

  get '/ynab', to: redirect("/auth/ynab"), as: '/ynab'
  get "/auth/ynab/callback", to: "register#index"

  get '/login', to: 'login#new'
  post '/login', to: "login#create"
  delete '/logout', to: "login#destroy"

  get '/privacy', to: 'privacy#show'

  get '/register', to: 'register#index'
  post '/register', to: 'register#create'

  get 'verification/:id/edit', to: 'verification#edit', as: 'edit_verification'
  patch '/verification/:id', to: 'verification#update', as: 'verification'

  get '/preferences', to: 'preferences#index'
  put '/preferences', to: 'preferences#update'

  get '/phone', to: 'phone#index'

  resources :users, only: [:create, :update, :new, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget
  attr_reader :name

  def initialize(name, balance)
    @name = name
    @balance = balance
  end

  def balance
    @balance/1000.00
  end


end

app/models/location.rb
class Location
  attr_reader :name, :types

  def initialize(attrs)
    @name = attrs[:name]
    @types = attrs[:types]
  end
end

app/models/message.rb
class Message < ApplicationRecord

  def self.random
    find(rand(1..Message.count))
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :phone_number, :username
  validates :phone_number, uniqueness: true, length: {is: 10}, numericality: true

  def self.daily_notification_users
    User.where(notifications: true)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :random_code

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def random_code
    rand(10000..99999).to_s
  end

  def twilio_verify(phone_number)
    session[:code] = random_code
    TwilioService.new.send_verification_code(phone_number,session[:code])
  end

  def code_verified
    params[:q] == session[:code]
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    if budget_params
      @facade = BudgetFacade.new({name: params[:name], types: params[:types]})
    end
    redirect_to '/' unless current_user
  end

private

  def budget_params
    params[:name] && params[:types]
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new
   if user = User.find_by(phone_number: params[:q])
     session[:user_id] = user.id
     twilio_verify(current_user.phone_number)
     redirect_to '/ynab'
   else
     flash[:error] = "We don't have that number in our system, please try again"
     redirect_to root_path
   end
  end

  def create
   if code_verified
     redirect_to dashboard_path
   else
     session.clear
     flash[:error] = "Verification code was incorrect. Please login again"
     redirect_to root_path
   end
  end

  def destroy
   session.clear
   flash[:message] = "You successfully logged out"
   redirect_to root_path
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  def index
    redirect_to '/' unless current_user
  end

  def update
    update_user
    if current_user.notifications
      flash[:notice] = "You are signed up for daily text notifications"
    else
      flash[:notice] = "You are no longer signed up for daily text notifications"
    end
    redirect_to dashboard_path
  end

private

  def update_user
    update = !current_user.notifications
    current_user.update(notifications: update)
  end
end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController

  def show 
  end

end

app/controllers/register_controller.rb
class RegisterController < ApplicationController

  def index
    if auth_hash
      session[:token] = auth_hash["credentials"]["token"]
      update_budget_id
      @direction = :login
    else
      @direction = :register
    end
  end

  def create
    if code_verified
      verify_user
      flash[:error] = "Please login to complete the registration process"
      redirect_to root_path
    else
      clear_user
      flash[:error] = "Verification code was incorrect. Please re-enter information"
      redirect_to new_user_path
    end
  end

  private
  def auth_hash
    request.env['omniauth.auth']
  end

  def get_id(token)
    service = YnabService.new({token: token})
    service.return_budget_id
  end

  def clear_user
    User.find(session[:user_id]).delete
    session.clear
  end

  def verify_user
    current_user.update(verified: true)
    session.clear
  end

  def budget_id
    get_id(session[:token])
  end

  def update_budget_id
    unless current_user.ynab_budget_id
      current_user.update(ynab_budget_id: budget_id)
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    redirect_to '/' unless current_user
    @facade = LocationSearchFacade.new(params[:location])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      twilio_verify(current_user.phone_number)
      redirect_to register_path
    else
      flash[:error] = "Please complete all fields and enter a unique and valid phone number"
      redirect_to new_user_path
    end
  end

  def edit
    @user = current_user
  end

  def update
    if code_verified
      current_user.update(phone_number: session[:new_phone_number])
      flash[:success] = "Phone number successfully updated"
      redirect_to dashboard_path
    else
      flash[:error] = "Verification code was incorrect. Phone number was not updated. Try again!"
      redirect_to edit_user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :phone_number)
  end

end

app/controllers/verification_controller.rb
class VerificationController < ApplicationController

  def edit
    @direction = "/users/#{current_user.id}"
  end

  def update
    session[:new_phone_number] = params[:user][:phone_number]
    twilio_verify(params[:user][:phone_number])
    redirect_to edit_verification_path(current_user)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<%= render "partials/nav" %>
<div class="center search">
  <button onclick="getLocation()" class="dark-text light-back button">Search Current Location</button>
</div>
<div class="budget_info center">
  <% if @facade %>
    <h2>Selected Location:</h2>
    <h3><%= @facade.location_name %></h3>
    <% @facade.location_budgets({budget_id: current_user.ynab_budget_id, token: session[:token]}).each do |budget| %>
      <p>You have <%= number_to_currency(budget.balance) %> left in your <%= budget.name %> budget</p>
    <% end %>
  <% end %>
</div>
<div class="center">
  <h2> My Phone Number: <%= current_user.phone_number %> </h2>
  <%= link_to "Update My Phone Number", edit_user_path(current_user)%><br>
  <%= link_to "Update My Daily Notifications", preferences_path %><br><br>
</div>

<div class="center">
    <%= button_to "Log Out", "/logout", method: :delete, class: "center dark-text light-back button" %>
</div>

app/views/partials/_nav.html.erb
<div class="nav">
  <%= link_to "thriftr", dashboard_path, class: "dark-text logo" %>
</div>

app/views/preferences/index.html.erb
<div class="center">
  <h2 class="dark-text ">Would You Like to Change Your Daily Notification Preference?</h2>
  <%= link_to "Yes!", preferences_path, method: :put, class: "light-back dark-text button center" %>
</div>

app/views/privacy/show.html.erb
<%= render "partials/nav" %>
<h1 class = "center dark-text">Privacy Policy</h1>

<p class="center dark-text privacy">
The Thriftr application does not directly request, handle or store any user's financial account credentials. With the exception of the YNAB user id, all data obtained through the YNAB API will not be stored in the Thriftr database.  Thriftr also guarantees that the data obtained through the YNAB API will not unknowingly be passed to any third-party.
</p>

app/views/register/index.html.erb
<%= render "partials/nav" %>
<h1 class="center dark-text">To complete registration enter code below below</h1>

<div class="center">
  <%= form_tag @direction, method: :post do %>
  <%= text_field_tag :q, nil, placeholder: "Enter Code", class: "center light-back input-field"%><br><br>
  <%= submit_tag "Verify", class: "light-back button" %>
  <%end%>
</div>

<h3 class = "center dark-text">If you do not receive a text, please click the button above to retry<h3>

app/views/results/index.html.erb
<%= render "partials/nav" %>

<h2 class="center locations-header">Select Your Current Location</h2>
<div class="locations center">
  <% if @facade.locations.size > 0 %>
    <% @facade.locations.each do |location| %>
      <div class="location">
        <p><%= link_to location.name, dashboard_path(name: location.name, types: location.types), class: "light-text link" %></p>
      </div>
    <% end %>
  <% else %>
    <p>No Locations Detected Nearby</p>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render "partials/nav" %>

<h1 class="center dark-text signup"> Please enter new phone number below</h1>
<h2 class="center dark-text prompt">When you click the button you will be sent a code to the submited phone number. Please submit code on the next page.</h2>
<div class="dark-text center input-form">
  <%= form_for @user, url: verification_path(@user) do |form| %>
    <%= form.text_field :phone_number, placeholder: "Phone Number", class: 'center light-back input-field'%><br><br>
    <%= form.submit "Update Phone Number", class: "dark-text light-back button" %>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render "partials/nav" %>

<h1 class="center dark-text signup"> Sign up for Thriftr</h1>
<h2 class="center dark-text prompt">When you click the button you will be sent a code to the submited phone number. Please submit code on the next page.</h2>
<div class="dark-text center input-form">
  <%= form_for @user do |form| %>
    <%= form.text_field :username, placeholder: "Username", class: 'center light-back input-field'%><br><br>
    <%= form.text_field :phone_number, placeholder: "Phone Number", class: 'center light-back input-field'%><br><br>
    <%= form.submit "Submit", class: "dark-text light-back button" %>
  <% end %>
</div>

app/views/verification/edit.html.erb
<%= render "partials/nav" %>
<h1 class="center dark-text">Enter code to verify updated phone nuumber</h1>

<div class="center">
  <%= form_tag @direction, method: :patch do %>
  <%= text_field_tag :q, nil, placeholder: "Enter Code", class: "center light-back input-field"%><br><br>
  <%= submit_tag "Verify", class: "light-back button" %>
  <%end%>
</div>

<h3 class = "center dark-text">If you do not receive a text, please click the button above to retry<h3>

app/views/verify/index.html.erb
<%= render "partials/nav" %>
<h1>To complete registration enter code below below</h1>

<%= form_tag :verify, method: :post do %>
  <%= text_field_tag :q, "Enter Code"%>
  <%= submit_tag "Verify" %>
<%end%>

app/views/welcome/index.html.erb
<h1 class="center main-logo">thriftr</h1>

<div class="center login">
  <%= form_tag :login, method: :get, action: :new do %>
  <%= text_field_tag :q, nil, placeholder: 'Phone Number', class: 'center light-back input-field'%><br><br>
  <%= submit_tag "Login", class: 'dark-text light-back button' %>
  <%end%>
</div>
<div class="center links">
  <%= link_to "Register here", new_user_path, class: 'dark-text link' %> <br><br>
  <%= link_to "Don't have a YNAB (You Need A Budget) account?", "https://www.youneedabudget.com/", class: 'dark-text link' %> <br><br>
  <%= link_to "Privacy Policy", '/privacy', class: 'dark-text link' %>
</div>